# Generated by Django 3.2.3 on 2024-06-22 20:44

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240610_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[profiles.models.validate_phone_number]),
        ),
    ]
