# Generated by Django 3.2.3 on 2024-06-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, unique=True)),
                ('answer', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
