# Generated by Django 3.2.3 on 2024-06-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240614_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
